[package]
name = "phper"
version = "0.4.0-alpha.2"
authors = ["jmjoy <918734043@qq.com>"]
edition = "2021"
rust-version = "1.56"
description = "A library that allows us to write PHP extensions using pure Rust and using safe Rust whenever possible."
repository = "https://github.com/jmjoy/phper.git"
documentation = "https://docs.rs/phper"
license = "MulanPSL-2.0"
readme = "../README.md"
keywords = ["php", "binding", "extension", "module"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
clap = { version = "3.2.5", features = ["derive"] }
dashmap = "5.3.4"
derive_more = "0.99.17"
indexmap = "1.9.0"
once_cell = "1.12.0"
phper-alloc = { version = "0.4.0-alpha.2", path = "../phper-alloc" }
phper-macros = { version = "0.4.0-alpha.2", path = "../phper-macros" }
phper-sys = { version = "0.4.0-alpha.2", path = "../phper-sys" }
thiserror = "1.0.31"

[build-dependencies]
phper-build = { version = "0.4.0-alpha.2", path = "../phper-build" }
phper-sys = { version = "0.4.0-alpha.2", path = "../phper-sys" }
