[workspace]
members = [
    "phper",
    "phper-alloc",
    "phper-build",
    "phper-macros",
    "phper-sys",
    "phper-test",

    # internal
    "examples/hello",
    "examples/http-client",
    "examples/logging",
    "tests/integration",
]
