[workspace]
members = [
    "phper",
    "phper-alloc",
    "phper-build",
    "phper-macros",
    "phper-sys",
    "phper-test",

    # internal
    "examples/hello",
#    "examples/hello-class",
#    "examples/mini-curl",
]
