[package]
name = "phper-macros"
version = "0.3.0"
authors = ["jmjoy <918734043@qq.com>"]
edition = "2018"
description = "The proc-macros for phper crate."
repository = "https://github.com/jmjoy/phper.git"
license = "Unlicense"
keywords = ["php", "proc-macro"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = "1.0.2"
syn = { version = "1.0.11", features = ["full"] }
proc-macro2 = "1.0.6"

[dev-dependencies]
syn = { version = "1.0.11", features = ["full", "extra-traits"] }
