[package]
name = "phper-alloc"
version = "0.3.0"
authors = ["jmjoy <918734043@qq.com>"]
edition = "2018"
description = "Alloc related items for phper crate."
repository = "https://github.com/jmjoy/phper.git"
license = "Unlicense"
keywords = ["php", "alloc"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phper-sys = { version = "0.3.0", path = "../phper-sys" }

[build-dependencies]
phper-build = { version = "0.3.0", path = "../phper-build" }
