[package]
name = "http-client"
version = "0.0.0"
authors = ["jmjoy <918734043@qq.com>"]
edition = "2021"
rust-version = "1.56"
publish = false
license = "MulanPSL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.40"
bytes = "1.0.1"
indexmap = "1.6.2"
phper = { version = "0.4.0-alpha.2", path = "../../phper" }
reqwest = { version = "0.11.3", features = ["blocking", "cookies"] }
thiserror = "1.0.24"

[dev-dependencies]
phper-test = { version = "0.4.0-alpha.2", path = "../../phper-test" }
