[package]
name = "http-client"
version = "0.0.0"
authors = ["jmjoy <918734043@qq.com>"]
edition = "2021"
rust-version = "1.56"
publish = false
license = "MulanPSL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib", "cdylib"]

# This example is hack to used for integration tests.
[[example]]
name = "http-client"
path = "src/_reexport.rs"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.58"
bytes = "1.1.0"
indexmap = "1.9.1"
phper = { version = "0.4.0-alpha.3", path = "../../phper" }
reqwest = { version = "0.11.11", features = ["blocking", "cookies"] }
thiserror = "1.0.31"

[dev-dependencies]
phper-test = { version = "0.4.0-alpha.3", path = "../../phper-test" }
