[package]
name = "phper-test"
version = "0.2.0-alpha.2"
authors = ["jmjoy <918734043@qq.com>"]
edition = "2018"
description = "PHPer testing utilities."
repository = "https://github.com/jmjoy/phper.git"
license = "Unlicense"
keywords = ["php", "binding"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.5.2"
tempfile = "3.1.0"
