[package]
name = "phper-test"
version = "0.4.0-alpha.3"
authors = ["jmjoy <918734043@qq.com>"]
edition = "2021"
rust-version = "1.56"
description = "PHPer testing utilities."
repository = "https://github.com/jmjoy/phper.git"
license = "MulanPSL-2.0"
keywords = ["php", "binding"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
fpm = ["fastcgi-client", "tokio/full"]

[dependencies]
fastcgi-client = { version = "0.7.0", optional = true }
libc = "0.2.126"
once_cell = "1.12.0"
phper-macros = { version = "0.4.0-alpha.3", path = "../phper-macros" }
tempfile = "3.3.0"
tokio = { version = "1.19.2", optional = true }

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
all-features = true
