[package]
name = "phper-sys"
version = "0.2.0"
authors = ["jmjoy <918734043@qq.com>"]
edition = "2018"
description = "Low level PHP binding for Rust."
repository = "https://github.com/jmjoy/phper.git"
license = "Unlicense"
keywords = ["php", "binding"]

[build-dependencies]
bindgen = "0.52.0"
cc = "1.0.61"
