[package]
name = "phper-sys"
version = "0.3.1"
authors = ["jmjoy <918734043@qq.com>"]
edition = "2021"
rust-version = "1.56"
description = "Low level PHP binding for Rust."
repository = "https://github.com/jmjoy/phper.git"
license = "Unlicense"
keywords = ["php", "binding"]

[build-dependencies]
bindgen = "0.58.1"
cc = "1.0.61"
