[package]
name = "http-server"
version = "0.0.0"
authors = ["jmjoy <918734043@qq.com>"]
edition = "2018"
publish = false
license = "Unlicense"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
hyper = { version = "0.14.8", features = ["http1", "runtime", "server"] }
phper = { version = "0.3.0", path = "../../phper" }
thiserror = "1.0.24"
tokio = { version = "1.6.0", features = ["full"] }

[dev-dependencies]
phper-test = { version = "0.3.0", path = "../../phper-test" }
reqwest = "0.11.3"
