[package]
name = "http-server"
version = "0.0.0"
authors = ["jmjoy <918734043@qq.com>"]
edition = "2021"
rust-version = "1.56"
publish = false
license = "MulanPSL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
hyper = { version = "0.14.19", features = ["http1", "runtime", "server"] }
phper = { version = "0.4.0-alpha.2", path = "../../phper" }
thiserror = "1.0.31"
tokio = { version = "1.19.2", features = ["full"] }

[dev-dependencies]
phper-test = { version = "0.4.0-alpha.2", path = "../../phper-test" }
reqwest = "0.11.11"
