name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always
#  RUST_BACKTRACE: 1
#  RUST_LOG: debug
  RUSTFLAGS: "-D warnings"

jobs:
  ci:
    name: CI
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        php-version:
          - 7.0
          - 7.1
          - 7.2
          - 7.3
          - 7.4

    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: php-config

      - name: PHP Config
        run: php-config --version && php-config --phpapi && php --version

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly-2020-11-09
            override: true
            components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
          
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --nocapture

      - uses: actions-rs/cargo@v1
        with:
          command: doc
