name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUST_LOG: debug
  RUSTFLAGS: "-D warnings"

jobs:
  ci:
    name: CI
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        php-version:
          - 7.3
          - 7.4

    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Checkout
        uses: actions/checkout@v2
